name: Publish to Registry
on:
  release:
      types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: login
        shell: bash
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        shell: bash
        run: docker build . --tag toloco/pgbouncer:$RELEASE_VERSION

      - name: Push
        shell: bash
        run: docker push toloco/pgbouncer:$RELEASE_VERSION
